//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrariyOtomation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbLibraryOtomationEntities2 : DbContext
    {
        public DbLibraryOtomationEntities2()
            : base("name=DbLibraryOtomationEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblBook> TblBook { get; set; }
        public virtual DbSet<TblBookSave> TblBookSave { get; set; }
        public virtual DbSet<TblPublisher> TblPublisher { get; set; }
        public virtual DbSet<TblWriter> TblWriter { get; set; }
    }
}
