//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrariyOtomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBookSave
    {
        public short BookSaveID { get; set; }
        public Nullable<short> WriterID { get; set; }
        public Nullable<short> PublisherID { get; set; }
        public Nullable<short> BookID { get; set; }
        public Nullable<byte> BookValume { get; set; }
        public Nullable<short> BookPage { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
        public Nullable<short> BookPublishedYear { get; set; }
        public string BookStuation { get; set; }
        public Nullable<System.DateTime> BookRegistrationDate { get; set; }
        public string BookType { get; set; }
    
        public virtual TblBook TblBook { get; set; }
        public virtual TblPublisher TblPublisher { get; set; }
        public virtual TblWriter TblWriter { get; set; }
    }
}
